name: tunerstudio
version: 3.1.04
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  tunerstudio:
    after: [desktop-gtk2]
    command: desktop-launch $SNAP/usr/bin/TunerStudioMS/TunerStudio.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$PATH
    
    plugs:
      - network
      - home
      - raw-usb
      - removable-media
      - x11
      - unity7
      - opengl
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      - audio-playback
      
parts:
  tunerstudio:
    source: https://www.efianalytics.com/TunerStudio/download/TunerStudioMS_v3.1.04.tar.gz
    source-type: tar
    plugin: nil

    override-build: |
      set -xe
      wget -O TunerStudio.tar.gz https://www.efianalytics.com/TunerStudio/download/TunerStudioMS_v3.1.04.tar.gz
      tar xvzf TunerStudio.tar.gz
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/usr/bin/TunerStudioMS/
      mv TunerStudioMS/* "$SNAPCRAFT_PART_INSTALL"/usr/bin/TunerStudioMS/
      
    build-packages:
      - openjdk-8-jre
      - wget
      - tar
      - librxtx-java
      
    stage-packages:
      - openjdk-8-jre
      - librxtx-java
      - fontconfig
      - fontconfig-config
      - libfontconfig1
      - x11-xserver-utils
