name: tunerstudio
version: 3.1.04
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  tunerstudio: 
    command: desktop-launch $SNAP/launch
    extensions: [gnome-3-34] 
    plugs:
      - network
      - home
      - raw-usb
      - removable-media
      - x11
      - unity7
      - opengl
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      - audio-playback
      
  tunerstudio:
    source: https://github.com/kz6fittycent/TunerStudio-snap
    source-type: git
    plugin: nil
    
    build-packages:
      - openjdk-8-jre
      - wget
      - tar
      - librxtx-java
      
    stage-packages:
      - openjdk-8-jre
      - librxtx-java
      - fontconfig
      - fontconfig-config
      - libfontconfig1
      - x11-xserver-utils
      - curl
      - tar

  publish:
    plugin: dump
    source: .
