name: tunerstudio
version: 3.1.04
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  tunerstudio:
    extensions: [gnome-3-28]
    command: /bin/sh $SNAP/usr/bin/TunerStudio/TunerStudio.sh
    plugs:
      - network
      - home
      - raw-usb
      - removable-media
      - x11
      - unity7
      - opengl
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      
parts:
  tunerstudio:
    source: https://www.efianalytics.com/TunerStudio/download/TunerStudioMS_v3.1.04.tar.gz
    source-type: tar
    plugin: dump
    organize:
      TunerStudioMS: usr/bin/TunerStudioM
    override-build: |
      tar xvzf TunerStudioMS_v3.1.04.tar.gz
#    override-pull: |
#      snapcraftctl pull
#      snapcraftctl set-version "$(curl -fsSL https://www.efianalytics.com/TunerStudio/download | grep -i "tar.gz" | cut -d ">" -f2 | cut -d "v" -f2 | cut -d "." -f1,2,3)"
    
    build-packages:
      - openjdk-11-jre-headless
      - bash
    
    stage-packages:
      - openjdk-11-jre-headless
      - bash
