name: tunerstudio
version: 3.1.04
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  tunerstudio:
    extensions: [gnome-3-28]
    command: /bin/sh $SNAP/usr/bin/TunerStudio/TunerStudio.sh
    plugs:
      - network
      - home
      - raw-usb
      - removable-media
      - x11
      - unity7
      - opengl
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      
parts:
  tunerstudio:
    source: https://www.efianalytics.com/TunerStudio/download/TunerStudioMS_v3.1.04.tar.gz
    source-type: tar
    plugin: nil
    override-build: |
      wget -O TunerStudio.tar.gz https://www.efianalytics.com/TunerStudio/download/TunerStudioMS_v3.1.04.tar.gz
      tar xvzf TunerStudio.tar.gz
      cd TunerStudioMS_v3.1.04/
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/usr/bin/TunerStudioMS/
      mv $PWD/TunerStudioMS "$SNAPCRAFT_PART_INSTALL"/usr/bin/TunerStudioMS/
      chmod a+x "$SNAPCRAFT_PART_INSTALL"/usr/bin/TunerStudioMS/TunerStudio.sh
      
    build-packages:
      - openjdk-11-jre-headless
    
    stage-packages:
      - openjdk-11-jre-headless
