name: tunerstudio
version: 3.1.04
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  tunerstudio:
    extensions: [gnome-3-28]
    command: /bin/sh $SNAP/usr/bin/TunerStudioMS/TunerStudio.sh
    plugs:
      - network
      - home
      - raw-usb
      - removable-media
      - x11
      - unity7
      - opengl
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      
parts:
  tunerstudio:
    source: https://www.efianalytics.com/TunerStudio/download/TunerStudioMS_v3.1.04.tar.gz
    source-type: tar
    plugin: nil
    override-build: |
      set -xe
      wget -O TunerStudio.tar.gz https://www.efianalytics.com/TunerStudio/download/TunerStudioMS_v3.1.04.tar.gz
      tar xvzf TunerStudio.tar.gz
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/usr/bin/TunerStudioMS/
      mv TunerStudioMS/* "$SNAPCRAFT_PART_INSTALL"/usr/bin/TunerStudioMS/
      
    build-packages:
      - openjdk-11-jre-headless
      - wget
      - tar
      
    stage-packages:
      - openjdk-11-jre-headless
