name: tunerstudio
version: 3.1.04
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  tunerstudio: 
    extensions: [gnome-3-34] 
    command: bash $SNAP/launch
    plugs:
      - network
      - home
      - raw-usb
      - removable-media
      - x11
      - unity7
      - opengl
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      - audio-playback
      - pulseaudio  # compatibility with snapd <2.41
      
parts:
  launcher:
    plugin: dump
    source: scripts
    
  tool:
    plugin: nil     
  
    build-packages:
      - openjdk-8-jre
      - librxtx-java
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - openjdk-8-jre
      - librxtx-java
      - fontconfig
      - fontconfig-config
      - libfontconfig1
      - x11-xserver-utils
      - curl
      - tar
    
  # https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - tool
      - launcher
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
