name: tunerstudio
version: 3.1.04
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer.

  After installing, run the following commands:
  
  sudo snap connect tunerstudio:raw-usb
  sudo snap connect tunerstudio:removable-media
  
  This is NOT an officially supported snap from TunerStudio. It is basically an automated
  installer for the software on 64-bit Linux systems running snapd. 

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64

layout:
  /usr/bin/xprop:
    bind-file: $SNAP/usr/bin/xprop
  /usr/local/bin:
    bind-file: $SNAP_USER_DATA/TunerStudioMS

apps:
  tunerstudio: 
    extensions: 
      - gnome-3-34
    command: launch
    plugs:
      - network
      - network-bind
      - home
      - raw-usb
      - removable-media
      - opengl
      - browser-support
      - audio-playback
      - pulseaudio  # compatibility with snapd <2.41
      - x11
      - desktop
      - desktop-legacy
    environment:      
      JAVA_HOME: $SNAP/usr/lib/jvm/java-1.8.0-openjdk-amd64

parts:
  launcher:
    plugin: dump
    source: scripts
          
  tool:
    plugin: nil
    build-packages:
      - openjdk-8-jre
      - librxtx-java
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - openjdk-8-jre
      - librxtx-java
      - fontconfig
      - fontconfig-config
      - libfontconfig1
      - x11-xserver-utils
      - curl
      - tar
    
  # https://snapcraft-utils-library.readthedocs.io/en/latest/lib/cleanup.html
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - tool
      - launcher
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - core18
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
