name: tunerstudio
adopt-info: tunerstudio
summary: TunerStudio MS - an advanced MegaSquirt Tuning Software
description: |
  TunerStudio MS, the most most advanced and refined MegaSquirt Tuning software available.
  The registered and Lite! editions are the same installer.

base: core18
grade: stable
confinement: strict

apps:
  tunerstudio:
    command: sh $SNAP/bin/TunerStudio/TunerStudio.sh
    plugs:
      - network
      - home
      - network-bind
      - raw-usb
      
parts:
  tunerstudio:
    source: https://www.efianalytics.com/TunerStudio/download/TunerStudioMS_v3.1.04.tar.gz
    source-type: tar
    plugin: nil
    
    override-pull: |
      curl -fsSL https://www.efianalytics.com/TunerStudio/download | grep -i "tar.gz" | cut -d ">" -f2 | cut -d "v" -f2 | cut -d "." -f1,2,3
    
    build-packages:
      - openjdk-11-jre-headless
    
    stage-packages:
      - openjdk-11-jre-headless
    
  publish:
    plugin: dump
    source: .
    organize:
      ./TunerStudioMS: /bin/TunerStudioMS
